### ISSUE TITLE
How can i add a customer account number to the order number ?

### ISSUE THREAD

**Issue by weiss42** [quadra-informatique/Magento-Cybermut#12]
Hello,
Our accounancy departement is trying to match our credit card records with our customer accounts. As default , the order number is provided to the CIC bank by the cybermut extension, but we cannot add any other field.

Would it be possible to export both customer account number and order number as the full order number. 
I mean order number is 50000001 account number is 20000001. could we send a new variable made of both order and account numbers. the result will be 5000000120000001. 

please could you tell me if it is possible and so on which file ?

Many thanks 

Laurent

**Comment by mpasquin** [comment]
Hi Laurent,

In the file app/code/community/Quadra/Cybermut/Model/Payment.php, you have an array key named "texte-libre" which is set by default by the order description. I think you can chage/complete it to add the customer number.

Best regards,
Quadra Team

**Comment by weiss42** [comment]
Thanks Marine for your help.

I ll gave a go and let you kow If I manage to get it sorted.
